name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

  Install-System-Dependencies:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:    
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential default-libmysqlclient-dev

      - name: Install Python Dependencies
        run: pip install flask flask-mysql pytest

  Run-Test:
    runs-on: ubuntu-latest
    needs: [build-and-test, Install-System-Dependencies]
    steps:
      - run: pytest
