name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential default-libmysqlclient-dev

      - name: Install Python Dependencies
        run: pip install flask flask-mysql pytest

      - name: Run Tests
        run: pytest

